DROP DATABASE IF EXISTS ChatDB;
CREATE DATABASE ChatDB;
-- usar
USE ChatDB;

-- Creating the Table
CREATE TABLE random (
	id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    title VARCHAR(255) NOT NULL,
    rate DECIMAL(2, 1) UNSIGNED
);